### ISSUE TITLE
question about integration with webpack/vuejs

### ISSUE THREAD

**Issue by SebastienGras** [pieczorx/PaySafeCard#1]
Hello !

Sorry for asking but i'm new in js, nodejs, vuejs and not very good in english ^^
I have webpack, express, and vuejs.
I tried to implement your package im my application but i didn't succeed :/

```
./src/main.js
Module Error (from ./node_modules/eslint-loader/index.js):
]50;CurrentDir=C:\wamp64\www\minecraftStore
  ✘  http://eslint.org/docs/rules/no-unused-expressions  Expected an assignment or function call and instead saw an expression  
  src\main.js:20:1
  async () => {
   ^

```

It is possible to use with vuejs and webpack ? If yes have you fews indications to implement your package and use with vuejs plz (where i have to put your code in a webpack app) ?

Thank you for help ;)

**Comment by pieczorx** [comment]
I really recommend you to read about promises in javascript. 
This code snippet:
```javascript
const doSomething = async function() {
	const response = await psc.createPayment({/* Parameters */});
	console.log('Your response: ', response);
}
doSomething();
```
...in fact can be written as:
```javascript
psc.createPayment({/* Parameters */}).then(function(response) {
	console.log(response)
}).catch(function(error) {
	console.log(error)
})

```
Both of these code snippets above work the same way.

The easiest way to handle it in express is with `await`, here is an example:

```javascript
const express = require('express')
const bodyParser = require('body-parser')
const PaySafeCard = require('paysafecard');

const psc = new PaySafeCard({
  key: 'psc_123456789012345678901-123456789', //Paste your api key here
  environment: 'TEST' //or PRODUCTION
});

const app = express()

// Parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))

// Parse application/json
app.use(bodyParser.json())

// Our route
app.post('/create-payment', async function(req, res, next) {
	const paymentAmount = 49.99;
	const currency = req.body.currency;

	try {
		if(!['USD', 'EUR'].includes(currency)) {
			throw new Error('Invalid currency');
		}
		// get more payment details here etc

		//Request payment link from PaySafeCard
		const response = await psc.createPayment({
			currency: currency,
			amount: paymentAmount,
			/* More parameters */
		});
		console.log('Your response: ', response)
		res.status(200).send(`Your payment link: ${response.redirect.auth_url}`)
	} catch(e) {
		res.status(400).send(`Something went wrong: ${e.message}`)
		// or call next(e) if you handle errors later
	}
});
```

**Comment by SebastienGras** [comment]
Thank you very much :) yesterday i was not well awake ^^ i thought i had express in my application but i'have not yet installed it x)

I will install it and try your answer, thank you again for rapid answer

**Comment by pieczorx** [comment]
You're welcome, reopen this issue if you have some future questions about Promise usage ;D

**Comment by SebastienGras** [comment]
Thanks  to you for explanations its works :)
I had a single page app, it was because i understood nothing ^^

With express it works but i'm using localhost, and paysafecard asking me a notification_url.
Notification url to my localhost is not possible ?
