### ISSUE TITLE
question about integration with webpack/vuejs in localhost

### ISSUE THREAD

**Issue by SebastienGras** [pieczorx/PaySafeCard#2]
Thanks to you for explanations its works :)
I had a single page app, it was because i understood nothing ^^

With express it works but i'm using localhost, and paysafecard asking me a notification_url.
Notification url to my localhost is not possible ?

**Comment by pieczorx** [comment]
Notifications are a good way to boost performance, but not requiured. You should probably use setInterval function on your localhost or single endpoint (preferred) which checks and verifies payment on demand.

Let's say for example:
- User A starts payment with your local ID = 1
- After payment you redirect user A to `localhost/payment/1` which says 'Checking your payment...'
- It sends asynchronous request to `localhost/api/payment-status/1` each 10 seconds
- You get payment 1 from your database and check if it's already verified. If not you check payment status from PaySafeCard
- If it's completed you capture it, save this status to database and prompt user A that the payment has been completed

When you move onto production just set `notification` to `yourdomain.com/api/payment-status/1` and check if the request comes from user A or from PaySafeCard, and if it's not PaySafeCard just don't perform any action.
Remember, this is recommended but not required. :)

**Comment by SebastienGras** [comment]
Thank you again for your rapidity and for explanaitions :)
I tried to dont put notification url but it says to me : invalid request parameter.

I have created an endpoint (if i have understand what it is ^^) /notifications but i cant tell to paysafecard in parameter because i am on localhost
I have screen servicecenter.paysafecard.com : 
 
When i put :
```
      urls: {
        redirectSuccess: 'http://example.com/successUrl',
        redirectFailure: 'http://example.com/failureUrl',
        notification: 'http://example.com/notificationsUrl'
      },
```
![image](https://user-images.githubusercontent.com/45287021/49237861-7b8f5080-f3ff-11e8-93a0-1a892078848e.png)


And when i put localhost (i cant put express port, it say invalid request parameter too) :
```
      urls: {
        redirectSuccess: 'http://example.com/successUrl',
        redirectFailure: 'http://example.com/failureUrl',
        notification: 'http://localhost/notifications'
      },
```
![image](https://user-images.githubusercontent.com/45287021/49237921-a11c5a00-f3ff-11e8-9bac-cd4c51a134de.png)


So i can't continue integration while notifications don't work ?

**Comment by pieczorx** [comment]
Just replace `http://example.com/notificationsUrl` with `http://example.com` or any other domain that responds with 200 status. (Don't do it on production 📦, just for localhost testing purpose)

**Comment by SebastienGras** [comment]
I tried too but when i put http://example.com, i receive these error : 
![image](https://user-images.githubusercontent.com/45287021/49328908-317daa80-f578-11e8-84c9-b488b67c8e00.png)

I have send a message with contact page of paysafecard to have more details on the error (i have no more informations on the error).

**Comment by pieczorx** [comment]
I think you should just use timer to check your payment status which ticks let's say every 5 seconds.
Or maybe you should try your test from production server?
